apiVersion: batch/v1
kind: Job
metadata:
  generateName: rhdh-loadtest-
spec:
  ttlSecondsAfterFinished: 86400
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: loadtest
          image: quay.io/rhdh-community/rhdh-loadtest-generator
          env:
            - name: FORCE_COLOR
              value: "true"
            - name: COREPACK_HOME
              value: /tmp/corepack
            - name: HOME
              value: /tmp
            - name: PLAYWRIGHT_JSON_OUTPUT_DIR
              value: /tmp
            - name: PLAYWRIGHT_JSON_OUTPUT_FILE
              value: /tmp/test-results.json
          command: ["yarn", "playwright", "test", "--output", "/tmp/test-results"]
